import { expect } from "chai";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import hre from "hardhat";
import { exportArtifacts, EXPORTED_CONTRACTS } from "../scripts/export-artifacts";

function tmpDir(prefix: string): string {
    return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function extract(source: string, name: string): string {
    const m = source.match(new RegExp(`export const ${name} = ([\\s\\S]*?) as const;`));
    if (!m) throw new Error(`${name} not found`);
    return m[1];
}

describe("chain:export (scripts/export-artifacts.ts)", function () {
    it("writes <Contract>.ts with abi and bytecode identical to the Hardhat artifact, for PolicyVault and MockKRWT", async function () {
        const out = tmpDir("export-");

        const written = await exportArtifacts(out);

        expect([...EXPORTED_CONTRACTS]).to.deep.equal(["PolicyVault", "MockKRWT"]);
        expect(written.map((p) => path.basename(p))).to.deep.equal(["PolicyVault.ts", "MockKRWT.ts"]);
        for (const [name, prefix] of [
            ["PolicyVault", "policyVault"],
            ["MockKRWT", "mockKrwt"],
        ] as const) {
            const src = fs.readFileSync(path.join(out, `${name}.ts`), "utf8");
            const artifact = await hre.artifacts.readArtifact(name);
            expect(JSON.parse(extract(src, `${prefix}Abi`))).to.deep.equal(artifact.abi);
            expect(JSON.parse(extract(src, `${prefix}Bytecode`))).to.equal(artifact.bytecode);
            expect(src.startsWith("// Generated by chain/scripts/export-artifacts.ts")).to.equal(true);
        }
    });

    it("creates the output directory when it does not exist", async function () {
        const out = path.join(tmpDir("export-"), "nested", "generated");

        await exportArtifacts(out);

        expect(fs.existsSync(path.join(out, "PolicyVault.ts"))).to.equal(true);
    });
});
