import fs from "node:fs";
import path from "node:path";
import hre from "hardhat";

export const EXPORTED_CONTRACTS = ["PolicyVault", "MockKRWT"] as const;

export const DEFAULT_OUT_DIR = path.resolve(__dirname, "../../src/adapters/chain/generated");

const HEADER = "// Generated by chain/scripts/export-artifacts.ts from chain/build/artifacts — do not edit. Run `npm run chain:compile`.";

function exportPrefix(contractName: string): string {
    // PolicyVault → policyVault, MockKRWT → mockKrwt
    const leadingUpper = contractName.match(/^[A-Z][a-z]*/)?.[0] ?? contractName;
    const rest = contractName.slice(leadingUpper.length);
    const restCamel = rest.length > 0 ? rest[0] + rest.slice(1).toLowerCase() : "";
    return leadingUpper.toLowerCase() + restCamel;
}

export async function exportArtifacts(outDir: string = DEFAULT_OUT_DIR): Promise<string[]> {
    fs.mkdirSync(outDir, { recursive: true });
    const written: string[] = [];
    for (const name of EXPORTED_CONTRACTS) {
        const artifact = await hre.artifacts.readArtifact(name);
        const prefix = exportPrefix(name);
        const source =
            `${HEADER}\n\n` +
            `export const ${prefix}Abi = ${JSON.stringify(artifact.abi, null, 4)} as const;\n\n` +
            `export const ${prefix}Bytecode = ${JSON.stringify(artifact.bytecode)} as const;\n`;
        const file = path.join(outDir, `${name}.ts`);
        fs.writeFileSync(file, source, "utf8");
        written.push(file);
    }
    return written;
}

if (require.main === module) {
    exportArtifacts()
        .then((files) => {
            for (const f of files) console.log(`exported ${path.relative(process.cwd(), f)}`);
        })
        .catch((err) => {
            console.error(err);
            process.exitCode = 1;
        });
}
